//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TblEducation
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Bu alan zorunludur!")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Bu alan zorunludur!")]
        public string SubHead1 { get; set; }
        [Required(ErrorMessage = "Bu alan zorunludur!")]
        public string SubHead2 { get; set; }
        [Required(ErrorMessage = "Bu alan zorunludur!")]
        [StringLength(10, ErrorMessage = "En fazla 10 karakter olabilir")]
        public string GPA { get; set; }
        public string Date { get; set; }
    }
}
