//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblSkills
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Bu alan zorunludur!")]
        public string Skills { get; set; }
        [Required(ErrorMessage = "Bu alan zorunludur!")]
        public Nullable<byte> Ratio { get; set; }
        [Required(ErrorMessage = "Bu alan zorunludur!")]
        public string Icon { get; set; }
    }
}
