//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblSocialMedia
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Bu alan zorunludur!")]
        public string SMName { get; set; }
        [Required(ErrorMessage = "Bu alan zorunludur!")]
        public string SMLink { get; set; }
        [Required(ErrorMessage = "Bu alan zorunludur!")]
        public string SMIcon { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
